### ISSUE TITLE
How it works

### ISSUE THREAD

**Issue by AngelGordillo** [forestryio/jekyll-menus#11]
Hello, I'm trying also to make an easy menu with 2 levels, something like a book
-Main
-Chapter1
  -Chapter1.1
  -Chapter1.1
and so on...
My menu is this: 
	<nav>
<ul>
{% for item in site.menus.header %}
  <li class="menu-item-{{ loop.index }}">
    <a href="{{ item.url }}" title="Go to {{ item.title }}">{{ item.title }}</a>
  </li>
{% endfor %}
</ul>
      </nav>
-------------------------------------------
And my pages:
layout: default
menus:
  header:
    title: Main
    weight: 1
    parent: 
----------------------------------------
layout: default
menus:
  header:
    title: Child1
    weight: 2
    children: 

Maybe it's stupidly easy, but I can't
Also are my first steps with Jekyll :)

**Comment by envygeeks** [comment]
Hi @AngelGordillo can you explain the problem you are having?  I see source code an a mention of a problem but I don't see an explicit problem listed in your ticket.

Thanks!

**Comment by AngelGordillo** [comment]
Hi @envygeeks I have the code that I wrote and the result is 
![image](https://user-images.githubusercontent.com/30040940/31163686-ecf637d8-a8e3-11e7-918e-621535af03b7.png)
Then I would like to have a menu with childs, maybe I'm doing something wrong.
my question is, how can I make children and parents?
Thanks!

**Comment by envygeeks** [comment]
See: https://github.com/forestryio/jekyll-menus#sub-menus

**Comment by AngelGordillo** [comment]
Thanks @envygeeks now I understand it better. I'm working on it
