### ISSUE TITLE
Deprecation warning.

### ISSUE THREAD

**Issue by rdricco** [forestryio/jekyll-menus#3]
I got this when running Jekyll 3.3.1 (plugin installed via gem):
```
Deprecation: posts.select should be changed toposts.docs.select.
                    Called by C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-menus-0.2.1/lib/jekyll/menus.rb:82:in `block in _collection_menus'.
```
I don't know if is related but the plugin didn't work here.

**Comment by envygeeks** [comment]
Does it work when you downgrade to Jekyll 3.3.0? Or 3.2.x? If it does I'll have to ask you to take part of this upstream as they might have broken an old API in the middle of a minor release which isn't such a good idea.  On the deprecation, I'll cut a new release that fixes that warning ASAP.

**Comment by envygeeks** [comment]
Once you've answered the first part of my question (or provided more information) I'll finish out this ticket.

**Comment by rdricco** [comment]
Didn't work on 3.3.0, when i tried to run on 3.2.0, other plugin broke my build. I'll close this ticket and open a new one soon as I got more information.

**Comment by rdricco** [comment]
I tried to use Jekyll-menus on other project, worked fine on Jekyll 3.3.1.
